### ISSUE TITLE
ASIDataCompressor truncating compressed data

### ISSUE THREAD

**Issue by JHumphreyJr** [pokeb/asi-http-request#147]
The ASIDataCompressor as of commit (5d8a22b36be1f620574f) truncates the compressed data if the length exceeds half of the original data. The problem exists on line 86 where it checks "while (zStream.avail_in != 0)" and according to the documentation here http://www.zlib.net/manual.html it should be checking avail_out "while (zStream.avail_out == 0)".

This error is reproducible by turning on gzip compression for request.

**Comment by danielrhodes** [comment]
I can confirm this bug. Thanks for the fix!

**Comment by pokeb** [comment]
Fixed now, many thanks!

**Comment by rdominelli** [comment]
I am still seeing truncation on requests with compressed bodies. Seems to be sporadic, but I have seen this with the 5/15/ build

**Comment by danielrhodes** [comment]
@rdominelli I'm seeing the same thing.

**Comment by rdominelli** [comment]
I did some further digging using Charles (great tool btw) to monitor the request hitting the wire. The issue is not ASIHTTPRequest in my case.  It turns out to be a problem with the configuration of Amazon ELB on the web server back end. 

Rich

**Comment by pokeb** [comment]
I've noticed this directly conflicts with a previous commit. :(

https://github.com/pokeb/asi-http-request/commit/5d8a22b36be1f620574fb10353b0d9aa9aa8c562

It's been a while since I dug into the zlib stuff and I don't really want to lose this afternoon looking at this further... :)

I am going to reopen this because I'm not certain there isn't still a problem lurking here. If someone can send me a project or post some sample code that demonstrates the current code isn't working, I'd be very grateful.

Best,

Ben

**Comment by danielrhodes** [comment]
Has there been any update on this?
