### ISSUE TITLE
LLVM Compiler 3.0 Warnings (w/Fix!)

### ISSUE THREAD

**Issue by andrewtheis** [pokeb/asi-http-request#206]
Apple's LLVM compiler 3.0 produces multiple warnings on the Reachability.h file like this:

<pre>Reachability.h: warning: Semantic Issue: Declaration of 'struct sockaddr_in' will not be visible outside of this function</pre>

Thankfully the way to silence / fix this warnings is simple enough. Simply add this import to the Reachability.h file:

<pre>#import &lt;netinet/in.h&gt;</pre>

Hope this helps any devs out their running the latest & greatest Apple released monday. I'd branch and submit a pull request, but it seems like a lot of work for one line of code :)

**Comment by bonekrusher** [comment]
Awesome - thx

**Comment by pokeb** [comment]
Thanks to everyone who found this, it should be fixed now!

Best,

Ben

**Comment by leonardoobaptistaa** [comment]
thank you!

**Comment by pixelfreak** [comment]
This doesn't work for me. I am still seeing the warning. Xcode 4.2.1 Build 4D502. Any idea?

Update: Weird, I deleted the offending line, then undo, now warning is gone...
